### PR TITLE
Fixed broken links

### PR DESCRIPTION
**Pull request by gilan6**
'.md' was missing

### CODE REVIEW

**Comment by gilan6** [comment]
Internal links to *.md files were missing in index.md

**Review by jimmybrancaccio — COMMENTED** [review]
I've checked all four links and none of them require an `.md` extension. For example - https://wiki.r-selfhosted.com/learn/what-is-self-hosting/ loads and works fine here. Can you check and confirm again on your side?

**Comment by lilkidsuave** [comment]
> I've checked all four links and none of them require an `.md` extension. For example - https://wiki.r-selfhosted.com/learn/what-is-self-hosting/ loads and works fine here. Can you check and confirm again on your side?

Works for me.

**Comment by lilkidsuave** [comment]
> > I've checked all four links and none of them require an `.md` extension. For example - https://wiki.r-selfhosted.com/learn/what-is-self-hosting/ loads and works fine here. Can you check and confirm again on your side?
> 
> Works for me.

Screenshot_20240707_234950_Brave

**Comment by gilan6** [comment]
Hi Jimmy,
I falsely thought these links should be active from the github rendering.
I've removed my branch and pull request

Thanks!

**Pull request closed without merging**
